version: 2
jobs:
  no-error-kafka:
    docker:
    - image: cimg/openjdk:21.0.6
    steps:
    - checkout
    - run:
        command: ./.ci/no-error-kafka.sh
    - run:
        command: |
          ./.ci/validation.sh git-diff
          ./.ci/validation.sh ci-temp-check
workflows:
  test:
    jobs:
    - no-error-kafka
  version: 2
